_version = 0.1

[oop-ex-toy-robot-group]
activity_id = "oop-ex-toy-robot-group"

[team2]
members = [
    "ronemeec025@student.wethinkcode.co.za",
    "mpmaneec025@student.wethinkcode.co.za",
    "nhmboeec025@student.wethinkcode.co.za",
    "mamaleec025@student.wethinkcode.co.za",
    "zuguteec025@student.wethinkcode.co.za"
]

